### ISSUE TITLE
Cannot update most recent plugin release

### ISSUE THREAD

**Issue by proudcdnguy** [berkmancenter/amber_wordpress#21]
Good day, 

I received the following message when I attempted to upload the .zip file of the most recent plugin update (On the main Plugins page, I clicked on the Add New button then clicked on Upload Plugin button on the next page within my blog's Dashboard using Google Chrome):

"Unpacking the package…

Installing the plugin…

The package could not be installed. No valid plugins were found.

Plugin install failed."

Any assistance would be greatly appreciated.

**Comment by genevec** [comment]
Hiya--

Did you first unzip `amber_wordpress-master.zip`, compressing the `amber` folder inside to be named `amber.zip`, and then upload that? Or did you try to upload the `amber_wordpress-master.zip` directly into WordPress?

It's a bit of a messy process, but until we're hosted in the official plugin directory (soon! weeks!) and Amber can be added with one click, you'll need to follow these steps to install: 

> To install Amber, download the source code of the most recent stable release. Unzip (or otherwise  decompress) the file. Inside the file "amber_wordpress-master" there is another file named "amber." Re- compress the file named "amber". The source code should now be "amber.zip".
(https://github.com/berkmancenter/amber_wordpress/wiki/Installation)

If that's not the case, let me know and we'll dig around more to figure out why this is happening. And if that was the case, we're also interested in making the install docs more clear... it's a bit confusing for sure, all this unzipping and zipping and renaming business.

**Comment by proudcdnguy** [comment]
Hiya! 

That has fixed my issue. Thank you for the clarification :)
