### ISSUE TITLE
404 on Amber's JS and CSS files when viewing a WordPress post

### ISSUE THREAD

**Issue by aribn** [berkmancenter/amber_wordpress#25]
I just installed the Amber plugin for WordPress (4.4.1) and preserved links for a sample post. When I then viewed the post in my browser, I got 404 errors for Amber's JS file and CSS stylesheet. In both cases, the issue seems to be that the path requested include `/plugins/amber/` rather than `/plugins/amberlink/`. (`GET http://favorites.aribadernatal.com/wp-content/plugins/amber/js/amber.js`) As a result, clicking the link does not trigger any Amber behavior.

**Comment by jlicht** [comment]
Thanks for the report. I believe your diagnosis is correct, and we're working on getting the fix out.

**Comment by genevec** [comment]
We just pushed 1.4.1 on WordPress. Once you update, it should be working for you.

**Comment by aribn** [comment]
Those files are successfully loading after updating the plugin, but nothing happens when I hover over a link that has been archived. The Amber Dashboard shows that links were successfully snapshotted. I set Available Links and Unavailable Links both to the "hover" setting, but nothing happens when I hover over a an archived link. Wordpress site at  [http://favorites.aribadernatal.com](http://favorites.aribadernatal.com).

**Comment by genevec** [comment]
How many seconds have you set the "Hover delay" to notify the end user? For immediate display of preserved links, you might want to indicate 0 there.

If this isn't the problem, let me know and we'll keep digging.

**Comment by aribn** [comment]
It had been at 2 seconds. I changed both to 0 seconds, but still nothing pops up.

**Comment by genevec** [comment]
Hmm. @jlicht would you be able to look into this?

**Comment by jlicht** [comment]
It suspect that the regexp in the filter that examines a post before it's displayed to extract URLs is getting confused by the `target="_blank"` that's part of the links on those pages. It gets the URLs wrong, and therefore can't find a match.

We'll fix this by updating the regular expression

**Comment by aribn** [comment]
That worked! (I modified amber.php locally to test, loaded a post, and verified that the Amber popover appears when hovering over an archived link.) Thank you for tracking this down! 
![popover](https://cloud.githubusercontent.com/assets/34577/12740703/98f3d6c6-c92a-11e5-990a-77a72d734f18.png)
