### ISSUE TITLE
Geo-specific calls

### ISSUE THREAD

**Issue by genevec** [berkmancenter/amber_wordpress#28]
Only make the call if geo-specific features are enabled. Also setup the call so that execution is deferred until after the page loads, so it doesn’t impact load time.

**Comment by wetterfrosch** [comment]
Strong support; we actually consider to remove amber plugin only because of the fact that we can't completely disable the geoip-lookup -- as in: external request -- without getting into the code and having the issue after each update again.

**Comment by genevec** [comment]
Thank you for the feedback--this will be addressed in our next release. Stay tuned.

**Comment by jlicht** [comment]
Included in release 1.4.2
