### ISSUE TITLE
Fatal error on activate (PHP 5.2)

### ISSUE THREAD

**Issue by bomeara** [berkmancenter/amber_wordpress#29]
Upon trying to activate Amber on Wordpress, I get `Parse error: syntax error, unexpected T_STRING in /home2/bcomeara/public_html/phylometh.org/wp-content/plugins/amberlink/libraries/backends/aws/AmazonS3Storage.php on line 15`

I am using Version 1.4.1 of Amber on Wordpress 4.4.2. All plugins and themes are most recent version: the active plugins are Category Specific RSS Menu, Google Analytics Dashboard for WP, and iframe. I just did the Add Plugin option within Wordpress. When activation failed, I deleted the plugin and reinstalled it, and I'm getting the same error. I don't have (or plan to use) S3 storage.

**Comment by jlicht** [comment]
Do you know what version of PHP you are using?

**Comment by bomeara** [comment]
PHP 5.2

**Comment by bomeara** [comment]
[And, by the way, of course feel free to just close this ticket: I know the version of PHP I'm using is somewhat old, and it's of course reasonable if you only want to / are able to support the current version of languages. But I thought to at least report this issue in case it affects others.]

**Comment by genevec** [comment]
We've added this to our known issues list (https://github.com/berkmancenter/amber_wordpress/wiki/Known-Issues#PHP_52_and_older) but plan to address it in a future release.

**Comment by genevec** [comment]
This has been addressed in our current development version: https://wordpress.org/plugins/amberlink/developers/

While we're not supporting 5.2 (at this time!), Amber v1.4.2 now detects that a user is running PHP 5.2 or lower. It notifies the user upon install/activation and provides information on upgrading your library.

**Comment by genevec** [comment]
My mistake: It will still fail on install if a user is on PHP 5.2 or lower. But we're now including more library checks (including cURL) upon installation! Hope that's some consolation for this dev release? Apologies.

**Comment by signeredfield** [comment]
I'm having the same error with Amber version 1.4.2, and my host says they're running php 5.4.45 and WordPress 4.4.2.  I only have IntenseDebate, JetPack, and PostTeaser plugins active.  Will the development version solve the problem for me, or is it unsolved for versions of php higher than 5.2?

**Comment by jlicht** [comment]
Fixed in version 1.4.3

**Comment by genevec** [comment]
Hey @bomeara -- circling back on supporting 5.2. Good news! 1.4.3 is now up as a dev release.

Go ahead and try it, let us know what you think: https://downloads.wordpress.org/plugin/amberlink.1.4.3.zip

**Comment by bomeara** [comment]
This is great, thank you! I've installed and activated it successfully on two sites. Thank you all for your work on this, and for the tool in general.
