### ISSUE TITLE
Upgrading to 1.4.3 causes error including AmberDB

### ISSUE THREAD

**Issue by jlicht** [berkmancenter/amber_wordpress#36]
Issue: Earlier this week I updated the plugin for Wordpress to 1.4.3. After activating it, my WP site didn't load properly anymore. After the hearer nothing loads. Asked the ISP for help and this is the bug they reported:

`FastCGI: server "/var/run/php-fpm/php56/php-cgi" stderr: PHP message: PHP Warning: include_once(): Failed opening '/sites/warekennis.nl/www/wp-content/plugins/amberlink/libraries/AmberDB.php' for inclusion (include_path='.:/usr/local/php56/share/pear') in /sites/warekennis.nl/www/wp-content/plugins/amberlink/amber.php on line 106`

Copied from berkmancenter/amber_common#35

**Comment by jlicht** [comment]
The text in the error message must be cut off - the correct line number is `1064`

**Comment by genevec** [comment]
We're following up with the site owner, trying to replicate the error on a development environment run by his host.

**Comment by genevec** [comment]
User has reported this resolved with v1.4.4 upgrade.
