### ISSUE TITLE
Track page/post where links originate and show in dashboard

### ISSUE THREAD

**Issue by mispy** [berkmancenter/amber_wordpress#39]
Something that's probably pretty easy to implement and would make Amber immediately very useful to me is if it shows where broken links live, so I can go and fix them.

**Comment by genevec** [comment]
Hi! For that use case, I would recommend the modular and robust [Broken Link Checker](https://wordpress.org/plugins/broken-link-checker/). Support is strong, it gets upgraded frequently, and it's documented fairly well.

While I haven't used it personally, I've heard good things about it.
