### ISSUE TITLE
Support for custom post types

### ISSUE THREAD

**Issue by su** [berkmancenter/amber_wordpress#6]
The project I'm currently most interested in Amber for keeps most of its actually-important content in a CPT, which Amber doesn't scan(only posts and pages at the moment). Ideally, there'd be an option to *select* which post types should be examined, since in a site using many of them they might not all be relevant.

I had a bit of a hack and slash at this and got it working(for me) with a couple of questions to look at. Will try and send a PR in the next couple days.

**Comment by jlicht** [comment]
Integrated into release 1.4
